# -*- coding: utf-8 -*-
"""projekcik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOy7eNBgu7Lk2ptrm1CLblZ4aeyw1GNw
"""

# Importy

import pandas as pd
import numpy as np
import re
import missingno as msno
import random
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import xgboost as xgb

# Ustawienie random_state i random.seed dla odtwarzalności

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)



"""## **Wczytanie dancyh i ich wizualizacja**"""
train = pd.read_csv('data/pzn-rent-train.csv')
test = pd.read_csv('data/pzn-rent-test.csv')

print(train.describe(include='all'))
print(train.isnull().sum())

msno.bar(train)
msno.matrix(train)

"""## **Czyszczenie danych i ich imputacja**"""

col_zero = ['flat_rent', 'flat_deposit']
for df in [train, test]:
  df.replace([-999, -9], np.nan, inplace=True)
  df.replace("", np.nan, inplace=True)
  df[col_zero] = df[col_zero].replace(0, np.nan)

bool_cols = ['individual', 'flat_furnished', 'flat_for_students', 'flat_balcony',
             'flat_garage', 'flat_garden', 'flat_dishwasher', 'flat_internet', 'flat_closed_area']
for df in [train, test]:
  for col in bool_cols:
    df[col] = df[col].fillna(False)

def imputacja_pokoje(df):

  mask_2 = df['ad_title'].str.contains(r'2\s?-?\s?pok|dwu\s?pok|dwa\s?pok', case=False, na=False)
  df.loc[df['flat_rooms'].isna() & mask_2, 'flat_rooms'] = 2

  mask_3 = df['ad_title'].str.contains(r'3\s?-?\s?pok|trzy\s?pok', case=False, na=False)
  df.loc[df['flat_rooms'].isna() & mask_3, 'flat_rooms'] = 3

  mask_4 = df['ad_title'].str.contains(r'4\s?-?\s?pok|cztero\s?pok|cztery\s?pok', case=False, na=False)
  df.loc[df['flat_rooms'].isna() & mask_4, 'flat_rooms'] = 4

  mask_5 = df['ad_title'].str.contains(r'5\s?-?\s?pok|pięcio\s?pok', case=False, na=False)
  df.loc[df['flat_rooms'].isna() & mask_5, 'flat_rooms'] = 5

  mask_6 = df['ad_title'].str.contains(r'6\s?-?\s?pok|sześcio\s?pok', case=False, na=False)
  df.loc[df['flat_rooms'].isna() & mask_6, 'flat_rooms'] = 6

  mask_1 = df['ad_title'].str.contains(r'kawalerk|studi|mieszkan|lokum|apartament|will|\bpokój\b|\bpokoj\b|1\s?-?\s?pok', case=False, na=False)
  df.loc[df['flat_rooms'].isna() & mask_1, 'flat_rooms'] = 1

  mask_duzo = (df['flat_rooms'] >= 7)
  df.loc[mask_duzo, 'flat_rooms'] = 1

  return df

train = imputacja_pokoje(train)
test = imputacja_pokoje(test)
print(train['flat_rooms'].isnull().sum())
print(test['flat_rooms'].isnull().sum())

official_quarters = [
    'Antoninek', 'Zieliniec', 'Kobylepole', 'Chartowo', 'Fabianowo', 'Kotowo',
    'Główna', 'Głuszyna', 'Górczyn', 'Grunwald', 'Jeżyce', 'Junikowo', 'Kiekrz',
    'Krzesiny', 'Pokrzywno', 'Garaszewo', 'Krzyżowniki', 'Smochowice', 'Kwiatowe',
    'Ławica', 'Morasko', 'Radojewo', 'Naramowice', 'Ogrody', 'Piątkowo', 'Podolany',
    'Rataje', 'Sołacz', 'Stare Miasto', 'Winogrady', 'Starołęka', 'Minikowo',
    'Marlewo', 'Strzeszyn', 'Szczepankowo', 'Splawie', 'Krzesinki', 'Świerczewo',
    'Łazarz', 'Umultowo', 'Wilda', 'Winiary', 'Wola', 'Żegrze', 'Dębiec',
    'Nowe Miasto', 'Ostrów Tumski', 'Śródka', 'Zawady', 'Komandoria', 'Łacina'
]
official_quarters = sorted(list(set(official_quarters)), key=len, reverse=True)

area_pattern = r'(\d+(?:[.,]\d+)?)\s*(?:m2|m²|mkw)'

def uzupelnij_area_i_quarter(df):
  def procesuj_wiersz(row):
    title = str(row['ad_title']).lower()

    if pd.isna(row['flat_area']):
      match_obj = re.search(area_pattern, title)
      if match_obj:
        val = float(match_obj.group(1).replace(',', '.'))
        if 10 <= val <= 200:
          row['flat_area'] = val

    if pd.isna(row['quarter']):
      for q in official_quarters:
        if re.search(rf'\b{q.lower()}\b', title):
          row['quarter'] = q
          break
    return row

  return df.apply(procesuj_wiersz, axis=1)

train = uzupelnij_area_i_quarter(train)
test = uzupelnij_area_i_quarter(test)

counts = train['quarter'].value_counts()
popularne = counts[counts >= 10].index

for df in [train, test]:
    df['quarter'] = df['quarter'].apply(lambda x: x if x in popularne else 'Inne')

train['quarter_copy'] = np.nan
test['quarter_copy'] = np.nan

le = LabelEncoder()

mask_train = train['quarter'].notnull()
le.fit(train.loc[mask_train, 'quarter'])

quarter_map = dict(zip(le.classes_, range(len(le.classes_))))

train.loc[mask_train, 'quarter_copy'] = train.loc[mask_train, 'quarter'].map(quarter_map)

mask_test = test['quarter'].notnull()
test.loc[mask_test & ~test['quarter'].isin(quarter_map.keys()), 'quarter'] = np.nan

mask_test = test['quarter'].notnull()
test.loc[mask_test, 'quarter_copy'] = test.loc[mask_test, 'quarter'].map(quarter_map)

it_imp = IterativeImputer(random_state=42, min_value=0)
cols_numeric = ['flat_area', 'flat_rooms', 'quarter_copy', 'building_floor_num']

train[cols_numeric] = it_imp.fit_transform(train[cols_numeric])
test[cols_numeric] = it_imp.transform(test[cols_numeric])

for df in [train, test]:
    df['flat_rooms'] = df['flat_rooms'].round().astype(int)
    df['quarter_copy'] = df['quarter_copy'].round().astype(int)
    df['building_floor_num'] = df['building_floor_num'].round().astype(int)

rent_map = train.groupby('flat_rooms')['flat_rent'].median()
deposit_map = train.groupby('flat_rooms')['flat_deposit'].median()

rent_map_all = train['flat_rent'].median()
deposit_map_all = train['flat_deposit'].median()

train['flat_rent'] = train['flat_rent'].fillna(train['flat_rooms'].map(rent_map))
train['flat_deposit'] = train['flat_deposit'].fillna(train['flat_rooms'].map(deposit_map))

test['flat_rent'] = test['flat_rent'].fillna(test['flat_rooms'].map(rent_map))
test['flat_deposit'] = test['flat_deposit'].fillna(test['flat_rooms'].map(deposit_map))

train['flat_rent'] = train['flat_rent'].fillna(rent_map_all)
train['flat_deposit'] = train['flat_deposit'].fillna(deposit_map_all)
test['flat_rent'] = test['flat_rent'].fillna(rent_map_all)
test['flat_deposit'] = test['flat_deposit'].fillna(deposit_map_all)

train['quarter'] = le.inverse_transform(train['quarter_copy'].astype(int))
test['quarter'] = le.inverse_transform(test['quarter_copy'].astype(int))

prestige_names = (
    r'city park|wojskow[ay]|towarow[ay]|maraton|soln[ay]|za bramką|wejchert|atal|garbar|'
    r'plac wolności|chwaliszewo|bałtyk|wilsona|zajezdnia|bookowska|stary browar|'
    r'ostrów tumski|nowa wilda|perfumiarnia|manufaktura'
)

premium_words = (
        'apartament|premium|luksus|wysoki standard|modern|design|loft|penthouse|smart|'
        'klimatyzac|taras|widok|panorama|saun|siłowni|fitness|ochron|monitor|'
        'concierge|granit|marmur|podłogow|antresola'
    )

budget_words = r'tani|okazj|student|skromn|\bpokój\b|\bpokoj\b|odstepne|odstępne|prl'

for df in [train, test]:
    title_low = df['ad_title'].str.lower()

    df['is_prestige'] = title_low.str.contains(prestige_names, na=False).astype(int)
    df['is_premium']  = title_low.str.contains(premium_words, na=False).astype(int)
    df['is_budget']   = title_low.str.contains(budget_words, na=False).astype(int)

train.isnull().sum()
test.isnull().sum()

"""## **Modele RandomForest i XGBoost**"""

to_drop = ['id', 'ad_title', 'date_activ', 'date_modif', 'date_expire', 'price', 'quarter']
features = [col for col in train.columns if col.lower() not in to_drop]

X_train = train[features]
y_train = train['price']
X_test = test[features]

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
rf_pred = model.predict(X_test)

xgb_params = {
    'n_estimators': 1500,
    'learning_rate': 0.015,
    'max_depth': 7,
    'subsample': 0.8,
    'random_state': 42,
    'n_jobs': -1
}

y_train_log = np.log1p(train['price'])

model_xgb = xgb.XGBRegressor(**xgb_params)

model_xgb.fit(X_train, y_train_log)

predictions_log = model_xgb.predict(X_test)
xgb_pred = np.expm1(predictions_log)

final_pred = (rf_pred + xgb_pred) / 2
submission = pd.DataFrame({
    'ID': range(1, len(test) + 1),
    'TARGET': final_pred
})

submission.to_csv('submission.csv', index=False)

"""## **Sprawdzenie modeli za pomocą train_test_split i wykresu**"""

X = train[features]
y = train['price']

X_train_v, X_val, y_train_v, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# RandomForest
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_v, y_train_v)
rf_val_pred = rf_model.predict(X_val)

# XGBoost
y_train_v_log = np.log1p(y_train_v)
xgb_model = xgb.XGBRegressor(**xgb_params)
xgb_model.fit(X_train_v, y_train_v_log)

xgb_val_pred_log = xgb_model.predict(X_val)
xgb_val_pred = np.expm1(xgb_val_pred_log)


final_val_pred = (rf_val_pred + xgb_val_pred) / 2

mae = mean_absolute_error(y_val, final_val_pred)
rmse = np.sqrt(mean_squared_error(y_val, final_val_pred))
r2 = r2_score(y_val, final_val_pred)

print(f"MAE: {mae:.2f} zł")
print(f"RMSE: {rmse:.2f} zł")
print(f"R2 Score: {r2:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(y_val, final_val_pred, alpha=0.5, color='blue')
plt.plot([y.min(), y.max()], [y.min(), y.max()], color='red', lw=2) # linia idealna
plt.xlabel("Prawdziwe ceny")
plt.ylabel("Przewidziane ceny")
plt.show()